--- #YAML:1.0
name:                Cache-Memcached-Tie
version:             0.07
abstract:            Use Cache::Memcached::Fast like hash.
license:             ~
author:              
    - Andrew Kostenko <gugu@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cache::Memcached::Fast:        0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
